services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: talent-platform
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - app-network-dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis_data_dev:/data
    networks:
      - app-network-dev

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/talent-platform?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5001:5001"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network-dev

volumes:
  mongodb_data_dev:
  redis_data_dev:

networks:
  app-network-dev:
    driver: bridge